pip install urllib3==1.25.11

nohup streamlit run Home.py > streamlit.log 2>&1 & 

> streamlit.log: This part of the command redirects standard output (stdout) of the streamlit run Home.py command to the file streamlit.log. 
This means any normal output, such as print statements or information messages generated by your Streamlit application, will be written to streamlit.log.

2>&1: This part redirects standard error (stderr) to the same location as standard output (>&1). 
Therefore, any error messages, exceptions, or warnings that would normally be printed to the terminal will also be appended to streamlit.log.
